import { setupLocale } from "../localizationManager";

export var farsiStrings = {
  groupButton: "گروه بندی با",
  ungroupButton: "حذف گروه",
  selectButton: "انتخاب",
  hideColumn: "مخفی کردن ستون",
  showColumn: "نمایش ستون",
  makePrivateColumn: "خصوصی کردن ستون",
  makePublicColumn: "عمومی کردن ستون",
  moveToDetail: "انتقال به جزئیات",
  showAsColumn: "نمایش به عنوان ستون",
  filterPlaceholder: "جستجو...",
  removeRows: "حذف سطرها",
  showLabel: "نمایش",
  entriesLabel: "ورودی",
  visualizer_text: "متون در جدول",
  visualizer_wordcloud: "ابر کلمات",
  visualizer_histogram: "هیستوگرام",
  visualizer_number: "متوسط",
  visualizer_choices: "جدول",
  visualizer_selectBase: "نمودار",
  // visualizer_matrix: "Chart",
  chartType_bar: "میله ای",
  chartType_vbar: "نوار عمودی",
  chartType_stackedbar: "نوار پشته",
  chartType_doughnut: "دونات",
  chartType_pie: "دابره ای(pie)",
  chartType_scatter: "پراکندگی(Scatter)",
  chartType_gauge: "عقربه ای",
  chartType_bullet: "Bullet",
  hideButton: "مخفی",
  makePrivateButton: "خصوصی کردن",
  makePublicButton: "عمومی کردن",
  showButton: "نمایش",
  filter: "فیلتر",
  resetFilter: "بازنشانی فیلترها",
  changeLocale: "تغییر محلی",
  clearButton: "پاک کردن",
  addElement: "انتخاب سوال برای نمایش...",
  defaultOrder: "ترتیب پیشفرض",
  ascOrder: "صعودی",
  descOrder: "نزولی",
  showMinorColumns: "نمایش ستونهای فرعی",
  otherCommentTitle: "سایر موارد و نظرات",
  showPercentages: "نمایش درصد",
  hidePercentages: "درصدهای مخفی",
  pdfDownloadCaption: "پی دی اف",
  xlsxDownloadCaption: "اکسل",
  csvDownloadCaption: "Csv",
  saveDiagramAsPNG: "دانلود طرح به عنوان یک فایل PNG",
  hideEmptyAnswers: "مخفی کردن پاسخهای خالی",
  showEmptyAnswers: "نمایش پاسخهای خالی",
  "topNValueText-1": "همه پاسخ ها",
  topNValueText5: "5 پاسخ برتر",
  topNValueText10: "10 پاسخ برتر",
  topNValueText20: "20 پاسخ برتر",
  hideMissingAnswers: "مخفی کردن پاسخهای گمشده",
  showMissingAnswers: "نمایش پاسخهای گمشده",
  missingAnswersLabel: "پاسخ های گمشده",
  noVisualizerForQuestion: "این نوع سوال هنوز تجسم نشده است",
  noResults: "هنوز نتیجه ای حاصل نشده است",
  showPerValues: "به ازای هر ارزش",
  showPerColumns: "در هر ستون",
  answer: "پاسخ",
  correctAnswer: "پاسخ صحیح: ",
  percent: "درصد",
  responses: "پاسخ"
};

setupLocale({ localeCode: "fa", strings: farsiStrings });
