import { setupLocale } from "../localizationManager";

export var norwegianStrings = {
  groupButton: "Grupper",
  ungroupButton: "Opphev gruppering",
  selectButton: "Velg",
  hideColumn: "Skjul kolonne",
  showColumn: "Vis kolonne",
  makePrivateColumn: "Gjør kolonne privat",
  makePublicColumn: "Gjør kolonne offentlig",
  moveToDetail: "Flytt til detaljert visning",
  showAsColumn: "Vis som kolonne",
  filterPlaceholder: "Søk...",
  removeRows: "Fjern rader",
  showLabel: "Vis",
  entriesLabel: "oppføringer",
  visualizer_text: "Tabellvisning",
  visualizer_wordcloud: "Ordsky",
  visualizer_histogram: "Histogram",
  visualizer_number: "Gjennomsnitt",
  visualizer_choices: "Bord",
  visualizer_selectBase: "Sjøkart",
  // visualizer_matrix: "Chart",
  chartType_bar: "Stolpediagram",
  chartType_vbar: "Vertikal stolpe",
  chartType_stackedbar: "Stablet stolpediagram",
  chartType_doughnut: "Hjuldiagram",
  chartType_pie: "Sektordiagram",
  chartType_scatter: "Punktdiagram",
  chartType_gauge: "Målediagram",
  chartType_bullet: "Kulediagram",
  hideButton: "Skjul",
  makePrivateButton: "Gjør privat",
  makePublicButton: "Gjør offentlig",
  showButton: "Vis",
  filter: "Filter",
  resetFilter: "Nullstill filter",
  changeLocale: "Bytt språk",
  clearButton: "Tøm",
  addElement: "Velg spørsmål...",
  defaultOrder: "Standard",
  ascOrder: "Stigende",
  descOrder: "Synkende",
  showMinorColumns: "Vis mindre kolonner",
  otherCommentTitle: "Annet og kommentarer",
  showPercentages: "Vis prosenter",
  hidePercentages: "Skjul prosenter",
  pdfDownloadCaption: "PDF",
  xlsxDownloadCaption: "Overgå",
  csvDownloadCaption: "CSV",
  saveDiagramAsPNG: "Last ned plott som en PNG-fil",
  hideEmptyAnswers: "Skjul tomme svar",
  showEmptyAnswers: "Vis tomme svar",
  "topNValueText-1": "Alle svar",
  topNValueText5: "Topp 5 svar",
  topNValueText10: "Topp 10 svar",
  topNValueText20: "Topp 20 svar",
  hideMissingAnswers: "Skjul manglende svar",
  showMissingAnswers: "Vis manglende svar",
  missingAnswersLabel: "Mangler svar",
  noVisualizerForQuestion: "Denne spørsmålstypen er ikke visualisert ennå",
  noResults: "Det er ingen resultater ennå",
  showPerValues: "Per verdier",
  showPerColumns: "Per kolonner",
  answer: "Svare",
  correctAnswer: "Riktig svar: ",
  percent: "Prosent",
  responses: "Svar"
};

setupLocale({ localeCode: "no", strings: norwegianStrings, nativeName: "Norsk" });