export declare const contrastTheme: {
    readonly themeName: "default-contrast";
    readonly cssVariables: {
        readonly "--sjs2-base-unit-size": "8px";
        readonly "--sjs2-base-unit-spacing": "8px";
        readonly "--sjs2-base-unit-radius": "8px";
        readonly "--sjs2-base-unit-border-width": "1px";
        readonly "--sjs2-base-unit-font-size": "8px";
        readonly "--sjs2-base-unit-line-height": "8px";
        readonly "--sjs2-base-unit-opacity": "1%";
        readonly "--sjs2-base-unit-scale": "1%";
        readonly "--sjs2-scale-x000": "calc(var(--sjs2-base-unit-scale) * 0)";
        readonly "--sjs2-scale-x025": "calc(var(--sjs2-base-unit-scale) * 25)";
        readonly "--sjs2-scale-x050": "calc(var(--sjs2-base-unit-scale) * 50)";
        readonly "--sjs2-scale-x075": "calc(var(--sjs2-base-unit-scale) * 75)";
        readonly "--sjs2-scale-x095": "calc(var(--sjs2-base-unit-scale) * 95)";
        readonly "--sjs2-scale-x100": "calc(var(--sjs2-base-unit-scale) * 100)";
        readonly "--sjs2-scale-x200": "calc(var(--sjs2-base-unit-scale) * 200)";
        readonly "--sjs2-size-x000": "calc(var(--sjs2-base-unit-size) * 0)";
        readonly "--sjs2-size-x025": "calc(var(--sjs2-base-unit-size) * 0.25)";
        readonly "--sjs2-size-x050": "calc(var(--sjs2-base-unit-size) * 0.50)";
        readonly "--sjs2-size-x075": "calc(var(--sjs2-base-unit-size) * 0.75)";
        readonly "--sjs2-size-x100": "calc(var(--sjs2-base-unit-size) * 1)";
        readonly "--sjs2-size-x150": "calc(var(--sjs2-base-unit-size) * 1.50)";
        readonly "--sjs2-size-x200": "calc(var(--sjs2-base-unit-size) * 2)";
        readonly "--sjs2-size-x250": "calc(var(--sjs2-base-unit-size) * 2.50)";
        readonly "--sjs2-size-x300": "calc(var(--sjs2-base-unit-size) * 3)";
        readonly "--sjs2-size-x350": "calc(var(--sjs2-base-unit-size) * 3.50)";
        readonly "--sjs2-size-x400": "calc(var(--sjs2-base-unit-size) * 4)";
        readonly "--sjs2-size-x500": "calc(var(--sjs2-base-unit-size) * 5)";
        readonly "--sjs2-size-x600": "calc(var(--sjs2-base-unit-size) * 6)";
        readonly "--sjs2-size-x700": "calc(var(--sjs2-base-unit-size) * 7)";
        readonly "--sjs2-size-x800": "calc(var(--sjs2-base-unit-size) * 8)";
        readonly "--sjs2-size-x900": "calc(var(--sjs2-base-unit-size) * 9)";
        readonly "--sjs2-size-x1000": "calc(var(--sjs2-base-unit-size) * 10)";
        readonly "--sjs2-size-x1100": "calc(var(--sjs2-base-unit-size) * 11)";
        readonly "--sjs2-size-x1200": "calc(var(--sjs2-base-unit-size) * 12)";
        readonly "--sjs2-size-x1300": "calc(var(--sjs2-base-unit-size) * 13)";
        readonly "--sjs2-size-x1400": "calc(var(--sjs2-base-unit-size) * 14)";
        readonly "--sjs2-size-x1500": "calc(var(--sjs2-base-unit-size) * 15)";
        readonly "--sjs2-radius-x000": "calc(var(--sjs2-base-unit-radius) * 0)";
        readonly "--sjs2-radius-x025": "calc(var(--sjs2-base-unit-radius) * 0.25)";
        readonly "--sjs2-radius-x050": "calc(var(--sjs2-base-unit-radius) * 0.50)";
        readonly "--sjs2-radius-x075": "calc(var(--sjs2-base-unit-radius) * 0.75)";
        readonly "--sjs2-radius-x100": "calc(var(--sjs2-base-unit-radius) * 1)";
        readonly "--sjs2-radius-x150": "calc(var(--sjs2-base-unit-radius) * 1.50)";
        readonly "--sjs2-radius-x200": "calc(var(--sjs2-base-unit-radius) * 2)";
        readonly "--sjs2-radius-x250": "calc(var(--sjs2-base-unit-radius) * 2.50)";
        readonly "--sjs2-radius-x300": "calc(var(--sjs2-base-unit-radius) * 3)";
        readonly "--sjs2-radius-x400": "calc(var(--sjs2-base-unit-radius) * 4)";
        readonly "--sjs2-radius-x500": "calc(var(--sjs2-base-unit-radius) * 5)";
        readonly "--sjs2-radius-x600": "calc(var(--sjs2-base-unit-radius) * 6)";
        readonly "--sjs2-radius-x700": "calc(var(--sjs2-base-unit-radius) * 7)";
        readonly "--sjs2-radius-x800": "calc(var(--sjs2-base-unit-radius) * 8)";
        readonly "--sjs2-radius-round": "9999px";
        readonly "--sjs2-spacing-x000": "calc(var(--sjs2-base-unit-spacing) * 0)";
        readonly "--sjs2-spacing-x025": "calc(var(--sjs2-base-unit-spacing) * 0.25)";
        readonly "--sjs2-spacing-x050": "calc(var(--sjs2-base-unit-spacing) * 0.50)";
        readonly "--sjs2-spacing-x075": "calc(var(--sjs2-base-unit-spacing) * 0.75)";
        readonly "--sjs2-spacing-x100": "calc(var(--sjs2-base-unit-spacing) * 1)";
        readonly "--sjs2-spacing-x150": "calc(var(--sjs2-base-unit-spacing) * 1.5)";
        readonly "--sjs2-spacing-x200": "calc(var(--sjs2-base-unit-spacing) * 2)";
        readonly "--sjs2-spacing-x250": "calc(var(--sjs2-base-unit-spacing) * 2.50)";
        readonly "--sjs2-spacing-x300": "calc(var(--sjs2-base-unit-spacing) * 3)";
        readonly "--sjs2-spacing-x400": "calc(var(--sjs2-base-unit-spacing) * 4)";
        readonly "--sjs2-spacing-x500": "calc(var(--sjs2-base-unit-spacing) * 5)";
        readonly "--sjs2-spacing-x600": "calc(var(--sjs2-base-unit-spacing) * 6)";
        readonly "--sjs2-spacing-x700": "calc(var(--sjs2-base-unit-spacing) * 7)";
        readonly "--sjs2-spacing-x800": "calc(var(--sjs2-base-unit-spacing) * 8)";
        readonly "--sjs2-spacing-negative-x025": "calc(var(--sjs2-base-unit-spacing) * -0.25)";
        readonly "--sjs2-spacing-negative-x050": "calc(var(--sjs2-base-unit-spacing) * -0.50)";
        readonly "--sjs2-spacing-negative-x075": "calc(var(--sjs2-base-unit-spacing) * -0.75)";
        readonly "--sjs2-spacing-negative-x100": "calc(var(--sjs2-base-unit-spacing) * -1)";
        readonly "--sjs2-spacing-negative-x150": "calc(var(--sjs2-base-unit-spacing) * -1.5)";
        readonly "--sjs2-spacing-negative-x200": "calc(var(--sjs2-base-unit-spacing) * -2)";
        readonly "--sjs2-spacing-negative-x250": "calc(var(--sjs2-base-unit-spacing) * -2.50)";
        readonly "--sjs2-spacing-negative-x300": "calc(var(--sjs2-base-unit-spacing) * -3)";
        readonly "--sjs2-spacing-negative-x400": "calc(var(--sjs2-base-unit-spacing) * -4)";
        readonly "--sjs2-spacing-negative-x500": "calc(var(--sjs2-base-unit-spacing) * -5)";
        readonly "--sjs2-spacing-negative-x600": "calc(var(--sjs2-base-unit-spacing) * -6)";
        readonly "--sjs2-spacing-negative-x700": "calc(var(--sjs2-base-unit-spacing) * -7)";
        readonly "--sjs2-spacing-negative-x800": "calc(var(--sjs2-base-unit-spacing) * -8)";
        readonly "--sjs2-opacity-x000": "calc(var(--sjs2-base-unit-opacity) * 0)";
        readonly "--sjs2-opacity-x005": "calc(var(--sjs2-base-unit-opacity) * 5)";
        readonly "--sjs2-opacity-x010": "calc(var(--sjs2-base-unit-opacity) * 10)";
        readonly "--sjs2-opacity-x015": "calc(var(--sjs2-base-unit-opacity) * 15)";
        readonly "--sjs2-opacity-x020": "calc(var(--sjs2-base-unit-opacity) * 20)";
        readonly "--sjs2-opacity-x025": "calc(var(--sjs2-base-unit-opacity) * 25)";
        readonly "--sjs2-opacity-x030": "calc(var(--sjs2-base-unit-opacity) * 30)";
        readonly "--sjs2-opacity-x035": "calc(var(--sjs2-base-unit-opacity) * 35)";
        readonly "--sjs2-opacity-x040": "calc(var(--sjs2-base-unit-opacity) * 40)";
        readonly "--sjs2-opacity-x045": "calc(var(--sjs2-base-unit-opacity) * 45)";
        readonly "--sjs2-opacity-x050": "calc(var(--sjs2-base-unit-opacity) * 50)";
        readonly "--sjs2-opacity-x055": "calc(var(--sjs2-base-unit-opacity) * 55)";
        readonly "--sjs2-opacity-x060": "calc(var(--sjs2-base-unit-opacity) * 60)";
        readonly "--sjs2-opacity-x065": "calc(var(--sjs2-base-unit-opacity) * 65)";
        readonly "--sjs2-opacity-x070": "calc(var(--sjs2-base-unit-opacity) * 70)";
        readonly "--sjs2-opacity-x075": "calc(var(--sjs2-base-unit-opacity) * 75)";
        readonly "--sjs2-opacity-x080": "calc(var(--sjs2-base-unit-opacity) * 80)";
        readonly "--sjs2-opacity-x085": "calc(var(--sjs2-base-unit-opacity) * 85)";
        readonly "--sjs2-opacity-x090": "calc(var(--sjs2-base-unit-opacity) * 90)";
        readonly "--sjs2-opacity-x095": "calc(var(--sjs2-base-unit-opacity) * 95)";
        readonly "--sjs2-opacity-x100": "calc(var(--sjs2-base-unit-opacity) * 100)";
        readonly "--sjs2-border-width-x000": "calc(var(--sjs2-base-unit-border-width) * 0)";
        readonly "--sjs2-border-width-x100": "calc(var(--sjs2-base-unit-border-width) * 1)";
        readonly "--sjs2-border-width-x200": "calc(var(--sjs2-base-unit-border-width) * 2)";
        readonly "--sjs2-border-width-x400": "calc(var(--sjs2-base-unit-border-width) * 4)";
        readonly "--sjs2-font-weight-regular": "Regular";
        readonly "--sjs2-font-weight-medium": "Medium";
        readonly "--sjs2-font-weight-semibold": "SemiBold";
        readonly "--sjs2-font-weight-bold": "Bold";
        readonly "--sjs2-font-size-x000": "calc(var(--sjs2-base-unit-font-size) * 0)";
        readonly "--sjs2-font-size-x100": "calc(var(--sjs2-base-unit-font-size) * 1)";
        readonly "--sjs2-font-size-x150": "calc(var(--sjs2-base-unit-font-size) * 1.5)";
        readonly "--sjs2-font-size-x200": "calc(var(--sjs2-base-unit-font-size) * 2)";
        readonly "--sjs2-font-size-x250": "calc(var(--sjs2-base-unit-font-size) * 2.5)";
        readonly "--sjs2-font-size-x300": "calc(var(--sjs2-base-unit-font-size) * 3)";
        readonly "--sjs2-font-size-x350": "calc(var(--sjs2-base-unit-font-size) * 3.5)";
        readonly "--sjs2-font-size-x400": "calc(var(--sjs2-base-unit-font-size) * 4)";
        readonly "--sjs2-font-size-x500": "calc(var(--sjs2-base-unit-font-size) * 5)";
        readonly "--sjs2-font-size-x600": "calc(var(--sjs2-base-unit-font-size) * 6)";
        readonly "--sjs2-line-height-x000": "calc(var(--sjs2-base-unit-line-height) * 0)";
        readonly "--sjs2-line-height-x100": "calc(var(--sjs2-base-unit-line-height) * 1)";
        readonly "--sjs2-line-height-x200": "calc(var(--sjs2-base-unit-line-height) * 2)";
        readonly "--sjs2-line-height-x300": "calc(var(--sjs2-base-unit-line-height) * 3)";
        readonly "--sjs2-line-height-x400": "calc(var(--sjs2-base-unit-line-height) * 4)";
        readonly "--sjs2-line-height-x500": "calc(var(--sjs2-base-unit-line-height) * 5)";
        readonly "--sjs2-line-height-x600": "calc(var(--sjs2-base-unit-line-height) * 6)";
        readonly "--sjs2-text-case-default": "none";
        readonly "--sjs2-text-case-uppercase": "uppercase";
        readonly "--sjs2-palette-gray-100": "#F5F5F5";
        readonly "--sjs2-palette-gray-150": "#EDEDED";
        readonly "--sjs2-palette-gray-200": "#E5E5E5";
        readonly "--sjs2-palette-gray-250": "#D4D4D4";
        readonly "--sjs2-palette-gray-300": "#CDCDCD";
        readonly "--sjs2-palette-gray-400": "#B3B2B2";
        readonly "--sjs2-palette-gray-500": "#8E8E8E";
        readonly "--sjs2-palette-gray-600": "#5F5E61";
        readonly "--sjs2-palette-gray-700": "#424146";
        readonly "--sjs2-palette-gray-750": "#36353C";
        readonly "--sjs2-palette-gray-800": "#2D2C33";
        readonly "--sjs2-palette-gray-900": "#1C1B20";
        readonly "--sjs2-palette-gray-999": "#111014";
        readonly "--sjs2-palette-gray-000": "#fff";
        readonly "--sjs2-palette-red-400": "#ff6e84";
        readonly "--sjs2-palette-red-600": "#E50A3E";
        readonly "--sjs2-palette-red-700": "#C30935";
        readonly "--sjs2-palette-green-400": "#15CDAB";
        readonly "--sjs2-palette-green-600": "#19B394";
        readonly "--sjs2-palette-green-700": "#15947A";
        readonly "--sjs2-palette-blue-400": "#66B4FC";
        readonly "--sjs2-palette-blue-600": "#437FD9";
        readonly "--sjs2-palette-blue-700": "#2A6CD0";
        readonly "--sjs2-palette-yellow-400": "#FEC64A";
        readonly "--sjs2-palette-yellow-600": "#FF9814";
        readonly "--sjs2-palette-yellow-700": "#F08700";
        readonly "--sjs2-palette-violet-400": "#C36FF4";
        readonly "--sjs2-palette-violet-600": "#A62CEC";
        readonly "--sjs2-palette-violet-700": "#9614E1";
        readonly "--sjs2-palette-olive-400": "#6FC648";
        readonly "--sjs2-palette-olive-600": "#4FAF24";
        readonly "--sjs2-palette-olive-700": "#41901E";
        readonly "--sjs2-palette-purple-400": "#A190FA";
        readonly "--sjs2-palette-purple-600": "#6E5BD1";
        readonly "--sjs2-palette-purple-700": "#5640C9";
        readonly "--sjs2-palette-indianred-400": "#F9786A";
        readonly "--sjs2-palette-indianred-600": "#AF496B";
        readonly "--sjs2-palette-indianred-700": "#973F5C";
        readonly "--sjs2-radius-semantic-form": "var(--sjs2-radius-x100)";
        readonly "--sjs2-radius-semantic-form-item": "var(--sjs2-radius-x050)";
        readonly "--sjs2-radius-control-action": "var(--sjs2-radius-semantic-form)";
        readonly "--sjs2-radius-control-action-icon": "var(--sjs2-radius-semantic-form)";
        readonly "--sjs2-radius-control-button": "var(--sjs2-radius-semantic-form)";
        readonly "--sjs2-radius-control-menu-item": "var(--sjs2-radius-semantic-form)";
        readonly "--sjs2-radius-control-drop-item": "var(--sjs2-radius-x100)";
        readonly "--sjs2-radius-control-checkbox": "var(--sjs2-radius-semantic-form-item)";
        readonly "--sjs2-radius-control-rating": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-ranking": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-ranking-item": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-toggle": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-toggle-item": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-track": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-track-item": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-control-track-thumb": "var(--sjs2-radius-round)";
        readonly "--sjs2-radius-container-panel": "var(--sjs2-radius-x200)";
        readonly "--sjs2-radius-container-panel-nested": "var(--sjs2-radius-x100)";
        readonly "--sjs2-radius-container-menu": "var(--sjs2-radius-x250)";
        readonly "--sjs2-radius-container-drop": "var(--sjs2-radius-x200)";
        readonly "--sjs2-radius-container-modal": "var(--sjs2-radius-x300)";
        readonly "--sjs2-radius-container-notifier": "var(--sjs2-radius-x200)";
        readonly "--sjs2-radius-container-tooltip": "var(--sjs2-radius-x100)";
        readonly "--sjs2-layout-control-formbox-small-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-formbox-small-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-formbox-small-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-formbox-medium-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-formbox-medium-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-formbox-medium-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-message-small-spacer": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-message-small-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-message-small-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-message-small-gap": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-message-medium-spacer": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-message-medium-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-message-medium-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-message-medium-gap": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-small-content-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-content-horizontal": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-small-swatch-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-swatch-left": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-small-swatch-right": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-input-small-icon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-icon-left": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-icon-right": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-input-small-label-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-label-horizontal": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-small-group-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-small-limit-vertical": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-input-small-limit-left": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-small-limit-right": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-content-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-content-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-input-medium-swatch-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-swatch-left": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-input-medium-swatch-right": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-input-medium-icon-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-icon-left": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-icon-right": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-input-medium-label-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-label-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-input-medium-group-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-input-medium-limit-vertical": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-input-medium-limit-left": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-input-medium-limit-right": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-action-xx-small-label-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-xx-small-label-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-xx-small-icon-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-xx-small-icon-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-xx-small-box-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-xx-small-box-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-xx-small-box-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-xx-small-addon-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-xx-small-addon-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-x-small-label-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-label-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-x-small-icon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-icon-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-box-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-box-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-box-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-x-small-addon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-x-small-addon-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-small-label-horizontal": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-action-small-label-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-small-icon-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-small-icon-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-small-box-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-action-small-box-horizontal": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-action-small-box-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-small-addon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-small-addon-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-medium-label-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-action-medium-label-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-medium-icon-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-medium-icon-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-medium-box-vertical": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-action-medium-box-horizontal": "var(--sjs2-spacing-x150)";
        readonly "--sjs2-layout-control-action-medium-box-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-medium-addon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-medium-addon-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-large-label-horizontal": "var(--sjs2-spacing-x200)";
        readonly "--sjs2-layout-control-action-large-label-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-large-icon-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-large-icon-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-large-box-vertical": "var(--sjs2-spacing-x200)";
        readonly "--sjs2-layout-control-action-large-box-horizontal": "var(--sjs2-spacing-x200)";
        readonly "--sjs2-layout-control-action-large-box-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-action-large-addon-vertical": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-action-large-addon-horizontal": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-caption-small-box-left": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-box-right": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-caption-small-box-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-box-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-caption-small-group-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-description-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-description-top": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-description-bottom": "var(--sjs2-spacing-x200)";
        readonly "--sjs2-layout-control-caption-small-caption-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-small-caption-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-control-caption-medium-box-left": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-box-right": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-caption-medium-box-vertical": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-box-gap": "var(--sjs2-spacing-x050)";
        readonly "--sjs2-layout-control-caption-medium-group-gap": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-description-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-description-top": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-description-bottom": "var(--sjs2-spacing-x200)";
        readonly "--sjs2-layout-control-caption-medium-caption-horizontal": "var(--sjs2-spacing-x000)";
        readonly "--sjs2-layout-control-caption-medium-caption-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-container-drop-horizontal": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-layout-container-drop-vertical": "var(--sjs2-spacing-x100)";
        readonly "--sjs2-size-semantic-xx-small": "var(--sjs2-size-x300)";
        readonly "--sjs2-size-semantic-x-small": "var(--sjs2-size-x400)";
        readonly "--sjs2-size-semantic-small": "var(--sjs2-size-x500)";
        readonly "--sjs2-size-semantic-medium": "var(--sjs2-size-x600)";
        readonly "--sjs2-size-semantic-large": "var(--sjs2-size-x700)";
        readonly "--sjs2-size-icon-small": "var(--sjs2-size-x200)";
        readonly "--sjs2-size-icon-medium": "var(--sjs2-size-x300)";
        readonly "--sjs2-size-icon-large": "var(--sjs2-size-x400)";
        readonly "--sjs2-is-panelless": "false";
        readonly "--sjs2-typography-font-family-default": "Open Sans";
        readonly "--sjs2-typography-font-family-code": "DM Mono";
        readonly "--sjs2-typography-font-size-small": "var(--sjs2-font-size-x150)";
        readonly "--sjs2-typography-font-size-default": "var(--sjs2-font-size-x200)";
        readonly "--sjs2-typography-font-size-medium": "var(--sjs2-font-size-x300)";
        readonly "--sjs2-typography-font-size-large": "var(--sjs2-font-size-x400)";
        readonly "--sjs2-typography-line-height-small": "var(--sjs2-line-height-x200)";
        readonly "--sjs2-typography-line-height-default": "var(--sjs2-line-height-x300)";
        readonly "--sjs2-typography-line-height-medium": "var(--sjs2-line-height-x400)";
        readonly "--sjs2-typography-line-height-large": "var(--sjs2-line-height-x500)";
        readonly "--sjs2-typography-font-weight-default": "var(--sjs2-font-weight-regular)";
        readonly "--sjs2-typography-font-weight-strong": "var(--sjs2-font-weight-semibold)";
        readonly "--sjs2-color-project-brand-400": "var(--sjs2-color-project-brand-600)";
        readonly "--sjs2-color-project-brand-600": "#3A179E";
        readonly "--sjs2-color-project-brand-700": "var(--sjs2-color-project-brand-600)";
        readonly "--sjs2-color-project-accent-400": "var(--sjs2-color-project-accent-600)";
        readonly "--sjs2-color-project-accent-600": "#3A179E";
        readonly "--sjs2-color-project-accent-700": "var(--sjs2-color-project-accent-600)";
        readonly "--sjs2-color-utility-body": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-utility-surface": "#F4F2FB";
        readonly "--sjs2-color-utility-plain": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-utility-sheet": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-utility-scrollbar": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-utility-a11y": "rgba(from var(--sjs2-palette-blue-400) r g b / var(--sjs2-opacity-x040))";
        readonly "--sjs2-color-utility-overlay-screen": "rgba(from var(--sjs2-palette-gray-700) r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-utility-overlay-border": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))";
        readonly "--sjs2-color-utility-shadow-small": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-utility-shadow-medium": "rgba(from #004C44 r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-utility-shadow-large": "rgba(from #004C44 r g b / var(--sjs2-opacity-x020))";
        readonly "--sjs2-color-bg-basic-primary": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-bg-basic-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))";
        readonly "--sjs2-color-bg-basic-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-basic-primary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))";
        readonly "--sjs2-color-bg-basic-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-basic-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-brand-primary": "var(--sjs2-color-project-brand-600)";
        readonly "--sjs2-color-bg-brand-secondary": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-brand-tertiary": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-brand-primary-dim": "var(--sjs2-color-project-brand-700)";
        readonly "--sjs2-color-bg-brand-secondary-dim": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-brand-tertiary-dim": "rgba(from var(--sjs2-color-project-brand-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-accent-primary": "var(--sjs2-color-project-accent-600)";
        readonly "--sjs2-color-bg-accent-secondary": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-accent-tertiary": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-accent-primary-dim": "var(--sjs2-color-project-accent-700)";
        readonly "--sjs2-color-bg-accent-secondary-dim": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-accent-tertiary-dim": "rgba(from var(--sjs2-color-project-accent-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-note-primary": "var(--sjs2-palette-blue-600)";
        readonly "--sjs2-color-bg-note-secondary": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-note-tertiary": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-note-primary-dim": "var(--sjs2-palette-blue-700)";
        readonly "--sjs2-color-bg-note-secondary-dim": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-note-tertiary-dim": "rgba(from var(--sjs2-palette-blue-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-neutral-primary": "var(--sjs2-palette-gray-900)";
        readonly "--sjs2-color-bg-neutral-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-neutral-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-neutral-primary-dim": "var(--sjs2-palette-gray-700)";
        readonly "--sjs2-color-bg-neutral-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-neutral-tertiary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x005))";
        readonly "--sjs2-color-bg-positive-primary": "var(--sjs2-palette-green-600)";
        readonly "--sjs2-color-bg-positive-secondary": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-positive-tertiary": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-positive-primary-dim": "var(--sjs2-palette-green-700)";
        readonly "--sjs2-color-bg-positive-secondary-dim": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-positive-tertiary-dim": "rgba(from var(--sjs2-palette-green-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-warning-primary": "var(--sjs2-palette-yellow-600)";
        readonly "--sjs2-color-bg-warning-secondary": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-warning-tertiary": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-warning-primary-dim": "var(--sjs2-palette-yellow-700)";
        readonly "--sjs2-color-bg-warning-secondary-dim": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-warning-tertiary-dim": "rgba(from var(--sjs2-palette-yellow-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-alert-primary": "var(--sjs2-palette-red-600)";
        readonly "--sjs2-color-bg-alert-secondary": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-alert-tertiary": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x000))";
        readonly "--sjs2-color-bg-alert-primary-dim": "var(--sjs2-palette-red-700)";
        readonly "--sjs2-color-bg-alert-secondary-dim": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-alert-tertiary-dim": "rgba(from var(--sjs2-palette-red-600) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-static-main-primary": "var(--sjs2-palette-gray-900)";
        readonly "--sjs2-color-bg-static-main-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-static-main-primary-dim": "var(--sjs2-palette-gray-700)";
        readonly "--sjs2-color-bg-static-main-secondary-dim": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-static-sub-primary": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-bg-static-sub-secondary": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x010))";
        readonly "--sjs2-color-bg-static-sub-primary-dim": "var(--sjs2-palette-gray-100)";
        readonly "--sjs2-color-bg-static-sub-secondary-dim": "rgba(from var(--sjs2-palette-gray-000) r g b / var(--sjs2-opacity-x015))";
        readonly "--sjs2-color-bg-state-common-disabled": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-fg-basic-primary": "var(--sjs2-palette-gray-900)";
        readonly "--sjs2-color-fg-basic-primary-alt": "var(--sjs2-palette-gray-700)";
        readonly "--sjs2-color-fg-basic-secondary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-fg-basic-tertiary": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))";
        readonly "--sjs2-color-fg-neutral-primary": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-fg-brand-primary": "var(--sjs2-color-project-brand-600)";
        readonly "--sjs2-color-fg-accent-primary": "var(--sjs2-color-project-accent-600)";
        readonly "--sjs2-color-fg-note-primary": "var(--sjs2-palette-blue-600)";
        readonly "--sjs2-color-fg-positive-primary": "var(--sjs2-palette-green-600)";
        readonly "--sjs2-color-fg-warning-primary": "var(--sjs2-palette-yellow-600)";
        readonly "--sjs2-color-fg-alert-primary": "var(--sjs2-palette-red-600)";
        readonly "--sjs2-color-fg-static-main-primary": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-fg-static-sub-primary": "var(--sjs2-palette-gray-900)";
        readonly "--sjs2-color-fg-state-common-disabled": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))";
        readonly "--sjs2-color-border-basic-primary": "var(--sjs2-palette-gray-900)";
        readonly "--sjs2-color-border-basic-secondary": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-border-brand-primary": "var(--sjs2-color-project-brand-600)";
        readonly "--sjs2-color-border-accent-primary": "var(--sjs2-color-project-accent-600)";
        readonly "--sjs2-color-border-note-primary": "var(--sjs2-palette-blue-600)";
        readonly "--sjs2-color-border-positive-primary": "var(--sjs2-palette-green-600)";
        readonly "--sjs2-color-border-warning-primary": "var(--sjs2-palette-yellow-600)";
        readonly "--sjs2-color-border-alert-primary": "var(--sjs2-palette-red-600)";
        readonly "--sjs2-color-border-neutral-primary": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-control-formbox-default-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-formbox-default-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-formbox-disabled-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-formbox-disabled-border": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-formbox-readonly-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-formbox-readonly-border": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-formbox-focused-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-formbox-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-formbox-invalid-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-formbox-invalid-border": "var(--sjs2-color-border-alert-primary)";
        readonly "--sjs2-color-control-formbox-highlighted-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-formbox-highlighted-border": "var(--sjs2-color-border-basic-primary)";
        readonly "--sjs2-color-control-input-default-line": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-input-default-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-input-default-placeholder": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-default-label": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-default-limit": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-default-icon": "var(--sjs2-color-fg-basic-tertiary)";
        readonly "--sjs2-color-control-input-disabled-line": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-disabled-value": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-disabled-placeholder": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-disabled-label": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-disabled-limit": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-disabled-icon": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-readonly-line": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-input-readonly-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-input-readonly-placeholder": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-readonly-label": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-readonly-limit": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-input-readonly-icon": "var(--sjs2-color-fg-basic-tertiary)";
        readonly "--sjs2-color-control-check-false-default-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-check-false-default-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-false-disabled-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-check-false-disabled-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-false-readonly-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-check-false-readonly-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-false-focused-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-check-false-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-check-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)";
        readonly "--sjs2-color-control-check-false-hovered-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-true-default-bg": "var(--sjs2-color-bg-brand-primary)";
        readonly "--sjs2-color-control-check-true-default-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-check-true-default-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-check-true-disabled-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-check-true-disabled-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-true-disabled-icon": "var(--sjs2-palette-gray-400)";
        readonly "--sjs2-color-control-check-true-readonly-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-check-true-readonly-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-check-true-readonly-icon": "var(--sjs2-palette-gray-400)";
        readonly "--sjs2-color-control-check-true-focused-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-check-true-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-check-true-focused-icon": "var(--sjs2-color-fg-brand-primary)";
        readonly "--sjs2-color-control-check-true-hovered-bg": "var(--sjs2-color-bg-brand-primary-dim)";
        readonly "--sjs2-color-control-check-true-hovered-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-check-true-hovered-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-segmented-false-default-bg": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))";
        readonly "--sjs2-color-control-segmented-false-default-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))";
        readonly "--sjs2-color-control-segmented-false-default-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-segmented-false-disabled-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-segmented-false-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))";
        readonly "--sjs2-color-control-segmented-false-disabled-value": "var(--sjs2-palette-gray-250)";
        readonly "--sjs2-color-control-segmented-false-readonly-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-segmented-false-readonly-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))";
        readonly "--sjs2-color-control-segmented-false-readonly-value": "var(--sjs2-palette-gray-400)";
        readonly "--sjs2-color-control-segmented-false-focused-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-segmented-false-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-segmented-false-focused-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-segmented-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)";
        readonly "--sjs2-color-control-segmented-false-hovered-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-segmented-false-hovered-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-segmented-true-default-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-segmented-true-default-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-segmented-true-default-value": "var(--sjs2-color-fg-brand-primary)";
        readonly "--sjs2-color-control-segmented-true-disabled-bg": "var(--sjs2-color-bg-basic-primary-dim)";
        readonly "--sjs2-color-control-segmented-true-disabled-border": "rgba(from var(--sjs2-color-border-basic-secondary) r g b / var(--sjs2-opacity-hidden))";
        readonly "--sjs2-color-control-segmented-true-disabled-value": "var(--sjs2-palette-gray-400)";
        readonly "--sjs2-color-control-segmented-true-readonly-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-segmented-true-readonly-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-segmented-true-readonly-value": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-control-segmented-true-focused-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-segmented-true-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-segmented-true-focused-value": "var(--sjs2-color-fg-brand-primary)";
        readonly "--sjs2-color-control-toggle-false-default-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-default-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-default-icon": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-disabled-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-disabled-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-disabled-icon": "var(--sjs2-color-fg-basic-tertiary)";
        readonly "--sjs2-color-control-toggle-false-readonly-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-readonly-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-readonly-icon": "var(--sjs2-color-fg-basic-tertiary)";
        readonly "--sjs2-color-control-toggle-false-focused-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-toggle-false-focused-icon": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-hovered-bg": "var(--sjs2-color-bg-basic-secondary-dim)";
        readonly "--sjs2-color-control-toggle-false-hovered-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-false-hovered-icon": "var(--sjs2-color-fg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-true-default-bg": "var(--sjs2-color-bg-brand-primary)";
        readonly "--sjs2-color-control-toggle-true-default-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-toggle-true-default-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-toggle-true-disabled-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-true-disabled-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-true-disabled-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-toggle-true-readonly-bg": "var(--sjs2-color-bg-basic-secondary)";
        readonly "--sjs2-color-control-toggle-true-readonly-border": "var(--sjs2-color-border-basic-secondary)";
        readonly "--sjs2-color-control-toggle-true-readonly-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-toggle-true-focused-bg": "var(--sjs2-color-bg-basic-primary)";
        readonly "--sjs2-color-control-toggle-true-focused-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-toggle-true-focused-icon": "var(--sjs2-color-fg-brand-primary)";
        readonly "--sjs2-color-control-toggle-true-hovered-bg": "var(--sjs2-color-bg-brand-primary-dim)";
        readonly "--sjs2-color-control-toggle-true-hovered-border": "var(--sjs2-color-border-brand-primary)";
        readonly "--sjs2-color-control-toggle-true-hovered-icon": "var(--sjs2-color-fg-static-main-primary)";
        readonly "--sjs2-color-control-message-bg": "var(--sjs2-color-bg-alert-secondary)";
        readonly "--sjs2-color-control-message-icon": "var(--sjs2-color-fg-alert-primary)";
        readonly "--sjs2-color-control-message-text": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-data-chart-bg-color-1": "#84CAD4";
        readonly "--sjs2-color-data-chart-bg-color-2": "#3A99FB";
        readonly "--sjs2-color-data-chart-bg-color-3": "#FF6771";
        readonly "--sjs2-color-data-chart-bg-color-4": "#1DB496";
        readonly "--sjs2-color-data-chart-bg-color-5": "#FFC152";
        readonly "--sjs2-color-data-chart-bg-color-6": "#ABA1FF";
        readonly "--sjs2-color-data-chart-bg-color-7": "#7D8CA5";
        readonly "--sjs2-color-data-chart-bg-color-8": "#4FC46C";
        readonly "--sjs2-color-data-chart-bg-color-9": "#E87BCB";
        readonly "--sjs2-color-data-chart-bg-color-10": "#4E6198";
        readonly "--sjs2-color-data-chart-bg-color-1-tinted": "rgba(from #84CAD4 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-2-tinted": "rgba(from #3A99FB r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-3-tinted": "rgba(from #FF6771 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-4-tinted": "rgba(from #1DB496 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-5-tinted": "rgba(from #FFC152 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-6-tinted": "rgba(from #ABA1FF r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-7-tinted": "rgba(from #7D8CA5 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-8-tinted": "rgba(from #4FC46C r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-9-tinted": "rgba(from #E87BCB r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-bg-color-10-tinted": "rgba(from #4E6198 r g b / var(--sjs2-opacity-x060))";
        readonly "--sjs2-color-data-chart-fg-on-color-1": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-2": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-3": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-4": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-5": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-6": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-7": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-8": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-9": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-fg-on-color-10": "var(--sjs2-palette-gray-000)";
        readonly "--sjs2-color-data-chart-border-color-1": "#84CAD4";
        readonly "--sjs2-color-data-chart-border-color-2": "#3A99FB";
        readonly "--sjs2-color-data-chart-border-color-3": "#FF6771";
        readonly "--sjs2-color-data-chart-border-color-4": "#1DB496";
        readonly "--sjs2-color-data-chart-border-color-5": "#FFC152";
        readonly "--sjs2-color-data-chart-border-color-6": "#ABA1FF";
        readonly "--sjs2-color-data-chart-border-color-7": "#7D8CA5";
        readonly "--sjs2-color-data-chart-border-color-8": "#4FC46C";
        readonly "--sjs2-color-data-chart-border-color-9": "#E87BCB";
        readonly "--sjs2-color-data-chart-border-color-10": "#4E6198";
        readonly "--sjs2-color-data-grid-fg-label": "var(--sjs2-color-fg-basic-primary)";
        readonly "--sjs2-color-data-grid-border-line": "#DCDCDC";
        readonly "--sjs2-color-data-grid-border-axis": "var(--sjs2-color-border-basic-primary)";
        readonly "--sjs2-opacity-visible": "var(--sjs2-opacity-x100)";
        readonly "--sjs2-opacity-hovered": "var(--sjs2-opacity-x100)";
        readonly "--sjs2-opacity-pressed": "var(--sjs2-opacity-x100)";
        readonly "--sjs2-opacity-disabled": "var(--sjs2-opacity-x025)";
        readonly "--sjs2-opacity-hidden": "var(--sjs2-opacity-x000)";
        readonly "--sjs2-border-width-default": "var(--sjs2-border-width-x100)";
        readonly "--sjs2-border-width-a11y": "var(--sjs2-border-width-x400)";
        readonly "--sjs2-border-width-hovered": "var(--sjs2-border-width-x100)";
        readonly "--sjs2-border-width-pressed": "var(--sjs2-border-width-x100)";
        readonly "--sjs2-border-width-focused": "var(--sjs2-border-width-x200)";
        readonly "--sjs2-border-width-highlighted": "var(--sjs2-border-width-x200)";
        readonly "--sjs2-border-width-disabled": "var(--sjs2-border-width-x100)";
        readonly "--sjs2-border-width-invalid": "var(--sjs2-border-width-x100)";
        readonly "--sjs2-border-width-readonly": "var(--sjs2-border-width-x100)";
    };
};
export default contrastTheme;
