resources:
  repositories:
    - repository: azurepipelines
      type: github
      endpoint: surveyjs
      name: surveyjs/azure-pipelines
      ref: refs/heads/analytics-scr-update

trigger: none
pr: none

extends:
  template: analytics.yml@azurepipelines
